version: '3.3'

services:

  #  WordPress latest version
  wordpress:
    image: wordpress:latest
    ports:
      - ${IP}:${WP_PORT}:80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DEBUG: 1
    working_dir: /var/www/html
    restart: always
    depends_on:
      - db

  #  command-line interface for WordPress
  wpcli:
    image: wordpress:cli
    user: xfs
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_IP: "${IP}"
      WORDPRESS_PORT: "${WP_PORT}"
      WORDPRESS_USER: "${WP_USER}"
      WORDPRESS_PASSWORD: "${WP_PASSWORD}"
      WORDPRESS_EMAIL: "${WP_USER_EMAIL}"
      WORDPRESS_SITE_TITLE: "${WP_SITE_TITLE}"
    depends_on:
      - db
      - wordpress

  #  phpMyAdmin
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:${PMA_PORT}:80
    links:
      - db:db

  db:
    image: mysql:5.7
    ports:
      - ${IP}:3306:3306
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    restart: always

volumes:
  db_data: