<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

require_once locate_template('/php/ThemeSpg.php');

$theme_spg = new ThemeSpg();
$theme_spg->init();